name: Main

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    name: Scrape Dean
    uses: ./.github/workflows/scrape-dean.yml
  release:
    name: Release
    permissions:
      contents: write
    needs: build
    uses: ./.github/workflows/release.yml