name: Scrape Dean

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  scrape-dean:
    name: Scrape Dean
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: actions/checkout@v3

      - name: Get date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: dean
          path: artifacts/

      - name: Setup outdir
        continue-on-error: true
        run: |
          mkdir artifacts

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run scraper
        run: |
          python3 all.py

      - name: Update artifacts
        run: |
          find . -name "*.csv" -exec bash -c 'file="$1"; rsync --max-size=$(stat -c '%s' "$file") "$file" "artifacts/$file"' _ {} \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dean
          path: artifacts/
          retention-days: 15

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.csv
          name: Weekly Release (${{ steps.date.outputs.date }})
          tag_name: ${{ steps.date.outputs.date }}
          body: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
