name: Scrape Dean

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup year matrix
        id: set-matrix
        run: |
          years=$(echo $(seq 11 $(date +'%y') | tr '\n' ',' | sed 's/,$//' | awk '{print "[" $0 "]"}'))
          echo "year_range=${years}" >> $GITHUB_OUTPUT
      - name: Echo matrix
        run: |
          echo "${{ steps.set-matrix.outputs.year_range }}"
    outputs:
      year_range: ${{ steps.set-matrix.outputs.year_range }}

  scrape-dean:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: ${{ fromJson(needs.build-matrix.outputs.year_range) }}
        semester: ["1", "2", "3"]
    steps:
      - name: Setup job
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Get run params
        id: get-run-params
        run: |
          start_year=${{ matrix.year }}
          end_year=$(expr ${start_year} + 1)
          semester=${{ matrix.semester }}
          echo "params=${start_year}-${end_year}-${semester}" >> $GITHUB_OUTPUT
      - name: Run scraper
        run: python3 main.py ${{ steps.get-run-params.outputs.params }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: collected
          path: ./*.csv
  release:
    needs: scrape-dean
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: collected
          path: artifacts/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.csv
          name: Release (${{ steps.date.outputs.date }})
          tag_name: ${{ steps.date.outputs.date }}
          body: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
