name: Scrape Dean

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  scrape-dean:
    name: Scrape Dean
    runs-on: ubuntu-latest
    steps:
      - name: Get date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Setup job
        uses: actions/checkout@v3

      - name: Create artifacts directory
        run: |
          mkdir artifacts

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run scraper
        run: |
          python3 all.py

      - name: Update artifacts
        run: |
          find . -name "*.csv" -exec bash -c 'file="$1"; rsync --max-size=$(stat -c '%s' "$file") "$file" "artifacts/$file"' _ {} \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dean
          path: artifacts

      - name: Publish to GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts
          name: Release (${{ steps.date.outputs.date }})
          tag: ${{ steps.date.outputs.date }}
